format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$fill\
$nodejs\
$python\
$time\
$cmd_duration\
\n$character"""

[fill]
symbol = " "

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "󰌾 "

[directory.substitutions]
"~" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"kaizntree" = "󱁕 "

[time]
format = '[ $time ]($style)'
style = "fg:#a0a9cb"
disabled = false
time_format = "%R"

[git_branch]
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[nodejs]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = " "

[python]
format = '[ ${symbol}${pyenv_prefix} (${version} )(\($virtualenv\) )]($style)'
style = "bg:#212736 fg:#769ff0"
symbol = ""
pyenv_prefix = ""

[cmd_duration]
min_time = 500
style = "fg:#a0a9cb"
format = "[$duration]($style)"
